spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb?currentSchema=public&reWriteBatchedInserts=true
    username: postgres
    password: root
  flyway:
    enabled: false
    baseline-on-migrate: true
  data:
    redis:
      url: ${redis-host}

  jpa:
    hibernate:
      # 量产阶段使用flyway 关闭 ddl-auto 改为validate
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.qq.com
    port: 465 # SSL 端口通常为 465，TLS 为 587
    username: 754369677@qq.com
    password: yjxfnjndtvpqbgad
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
wx:
  miniapp:
    appid: wx0c0e1b56a66e6e3b      # 你的小程序 AppID
    secret: 56fe21c4c920712af5eb991cb356695b    # 你的小程序 AppSecret
    # 自动将 AccessToken 等凭证缓存在 Redis 中 (多实例集群部署必备)
#    config-storage:
#      type: redis
#      redis:
#        host: 127.0.0.1
#        port: 6379
